function trackers=configTrackers

fprintf('************************************************************\n')
tracker_id = input('What are you doing: 1-Running our tracker; 2-Disply results\n************************************************************\n');

trackers1={   struct('name','CT','namePaper','CT'),...
    struct('name','TLD','namePaper','TLD'),...    
    struct('name','IVT','namePaper','IVT'),...
    struct('name','DFT','namePaper','DFT'),...%yellow
    struct('name','ASLA','namePaper','ASLA'),...
    struct('name','L1APG','namePaper','L1APG'),...    
    struct('name','ORIA','namePaper','ORIA'),...
    struct('name','MTT','namePaper','MTT'),...
    struct('name','CSK','namePaper','CSK'),...
    struct('name','SCM','namePaper','SCM'),...
    struct('name','LOT','namePaper','LOT')};

trackersEXE={ struct('name','CPF','namePaper','CPF'),...
    struct('name','Struck','namePaper','Struck'),...
    struct('name','MIL','namePaper','MIL'),...
    struct('name','OAB','namePaper','OAB'),...
    struct('name','SBT','namePaper','SemiT'),...
    struct('name','BSBT','namePaper','BSBT'),...
    struct('name','Frag','namePaper','Frag'),...
    struct('name','KMS','namePaper','KMS'),...
    struct('name','SMS','namePaper','SMS'),...
    struct('name','LSK','namePaper','LSK'),...
    struct('name','VTS','namePaper','VTS'),...
    struct('name','VTD','namePaper','VTD'),...
    struct('name','CXT','namePaper','CXT')};

trackersCompare = {...
    struct('name','MUSTer','namePaper','MUSTer'),...
    struct('name','STC','namePaper','STC'),...
    struct('name','HCF','namePaper','HCF'),...
    struct('name','DLT','namePaper','DLT'),...
    struct('name','LCT','namePaper','LCT'),...
    struct('name','DSST','namePaper','DSST'),...
    struct('name','MEEM','namePaper','MEEM'),...
    struct('name','TGPR','namePaper','TGPR'),...
    struct('name','KCF','namePaper','KCF')};

trackersOURS = {struct('name','SemanticTracking','namePaper','SemanticTracking')};

% trackers = [trackersVIVID,trackers1,trackersEXE];
switch tracker_id
    case 1
        trackers = [trackersOURS];
    case 2
        trackers = [trackersOURS, trackersCompare];
end
